In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("C:\\Users\\sarayu\\Desktop\\scs\\celebal_internship\\week_1\\Combined_dataset.csv")

In [4]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [5]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [6]:
df.shape

(1000, 24)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [8]:
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [9]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [10]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [11]:
df.isnull()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False

In [12]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [13]:
df['discount'] = df['discount'].fillna(df['discount'].median())

In [14]:
df['seller_name']=df['seller_name'].fillna('Unknown')

In [15]:
df["seller_information"] = df["seller_information"].fillna("Unknown")

In [16]:
df=df.drop(columns=['videos','variations','what_customers_said'])

In [17]:
df.drop_duplicates()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_details,breadcrumbs,product_specifications,amount_of_stars,seller_name,sizes,seller_information,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""description"":""Navy Blue solid backpackNon-Pa...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""description"":""Navy Blue backpackNon-Padded h...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""description"":""Pink solid backpacks Non-padd...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown,"[{""size"":""S""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""description"":""Navy and grey printed backpack...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""description"":""Blue solid bath robe, has a sh...","[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""description"":""Features:Nothing about the For...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""description"":""Pack Contains: single watchDis...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""description"":""Case style: Analogue watch, ha...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Dial Material"",""specif...","{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""description"":""Pack Contains: single watch D...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",Tru███m R███il,"[{""size"":""Onesize""}]",Sho███o. ███-10█████████enu███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""description"":""Set content: One yoga matColou...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Mat Thickness"",""specif...","{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",Unknown,"[{""size"":""Medium""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [18]:
df[["initial_price", "final_price"]].dtypes

initial_price    int64
final_price        str
dtype: object

In [19]:
df['final_price'].head()

0    "₹3,995.00"
1    "₹2,899.00"
2    "₹2,999.00"
3    "₹1,675.00"
4    "₹2,899.00"
Name: final_price, dtype: str

In [20]:
df['final_price']=df['final_price'].str.replace('₹',"")
df['final_price']=df['final_price'].str.replace(',',"")

In [21]:
df['final_price'].head()

0    "3995.00"
1    "2899.00"
2    "2999.00"
3    "1675.00"
4    "2899.00"
Name: final_price, dtype: str

In [22]:
df['final_price']=df['final_price'].str.replace('"','')

In [23]:
df['final_price'].head()

0    3995.00
1    2899.00
2    2999.00
3    1675.00
4    2899.00
Name: final_price, dtype: str

In [27]:
df['final_price']=pd.to_numeric(df['final_price'])

In [28]:
df['final_price'].dtypes

dtype('float64')

In [29]:
df['discount_percent']=((df['initial_price']-df['final_price'])/df['initial_price'])*100

In [32]:
df[["initial_price", "final_price","discount_percent"]]

     initial_price  final_price  discount_percent
0             3995       3995.0               0.0
1             2899       2899.0               0.0
2             2999       2999.0               0.0
3             1675       1675.0               0.0
4             2899       2899.0               0.0
..             ...          ...               ...
995          11890      11890.0               0.0
996           8900       8900.0               0.0
997           7950       7950.0               0.0
998           3295       2636.0              20.0
999            699        699.0               0.0

[1000 rows x 3 columns]

In [33]:
df[df["discount_percent"] > 0]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,seller_name,sizes,seller_information,best_offer,more_offers,category,discount_percent
11,18346118,Arrabi,Pink & White Graphic 300 TC King Bedsheet with...,0.0,0,3329,74.0,865.0,INR,http://assets.myntassets.com/assets/images/183...,...,"[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Sig███Ove███as,"[{""size"":""Super King""}]",Old███. 2███162█████████o. ███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets,74.016221
12,18327434,BELLA CASA,Unisex Blue Bedsheets,0.0,0,1499,73.0,404.0,INR,http://assets.myntassets.com/assets/images/183...,...,"[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Bel███Cas███ash█████████ail█████████,"[{""size"":""Single""}]",E-1███103███PIP█████████ IN███████████████████...,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets,73.048699
18,22409156,Kastner,Women Textured Tang Slim Belt,3.8,9,1399,84.0,223.0,INR,http://assets.myntassets.com/assets/images/224...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Belt Width"",""specifica...","{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",Kas███r L███her█████████Pvt██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",A-5███ADA███R V█████████ De█████████████████████,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",belts,84.060043
19,18985918,Tommy Hilfiger,Women Navy Blue Embroidered High-Neck Pure Cot...,4.1,11,2999,40.0,1799.0,INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...",PVH███VIN███ASH█████████TE ███████████████,"[{""size"":""XXS"",""value"":""21.8in"",""value_name"":""...",PVH███vin███ash█████████tdN███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bodysuit,40.013338
20,22120138,Ed-a-Mamma Baby,Infant Boys Pack Of 2 Printed Pure Cotton Body...,4.2,5,999,30.0,699.0,INR,http://assets.myntassets.com/assets/images/221...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",ETE███LIA███EAT█████████CHA███████████████████...,"[{""size"":""0-3M"",""value"":""18.9in"",""value_name"":...",1A ███I H███E S█████████CH ███████████████████...,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bodysuit,30.030030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,17697474,Timex,Women White Dial & Gold Toned Analogue Watch T...,4.9,8,1995,20.0,1596.0,INR,http://assets.myntassets.com/assets/images/176...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",TIM███T R███IL █████████RIV████████████,"[{""size"":""Onesize""}]","Fla███o. ███, 6█████████y C███████████████████...","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",watches,20.000000
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.0,3266.0,INR,http://assets.myntassets.com/assets/images/246...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...",DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","Fir███Flo███ Pl█████████, I███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,53.007194
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.0,3235.0,INR,http://assets.myntassets.com/assets/images/117...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",Fla███ech███tai███,"[{""size"":""Onesize""}]","3rd███165███th █████████, s███████████████████...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,10.013908
993,19322504,V2A,Girls Blue Printed Dial & Pink Straps Digital ...,4.0,6,1599,50.0,799.0,INR,http://assets.myntassets.com/assets/images/193...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",Br ███erp███es,"[{""size"":""Onesize""}]",Kha███ no███122█████████lhi██████████████████,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,50.031270
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",Tru███m R███il,"[{""size"":""Onesize""}]",Sho███o. ███-10█████████enu███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,20.000000

In [34]:
df["discount_percent"].value_counts()

discount_percent
0.000000     363
30.000000      7
60.060060      5
50.000000      5
74.042310      5
            ...
40.010003      1
50.005003      1
53.007194      1
10.013908      1
50.031270      1
Name: count, Length: 509, dtype: int64

In [36]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,seller_name,sizes,seller_information,best_offer,more_offers,category,discount_percent
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown,"[{""size"":""S""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,0.0

In [37]:
df.to_csv("cleaned_data.csv")