# Celebal Internship CEI 2026

## WEEK 3 - ASSIGNMENT

## Use Subqueries, CTEs, and Window Functions to analyze sales data from the Superstore dataset.

### Step 1: Setup Data

In [1]:
import pandas as pd
import sqlite3

Import the Superstore dataset into a table named superstore_raw.

In [2]:
conn = sqlite3.connect("superstore.db")
df = pd.read_csv("Sample_Superstore.csv",encoding = "latin1")
df.to_sql("superstore_raw",conn,if_exists = "replace",index=False)

9994

In [3]:
pd.read_sql("SELECT * FROM superstore_raw LIMIT 7",conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656

In [4]:
pd.read_sql("PRAGMA table_info(superstore_raw)",conn)

    cid           name     type  notnull dflt_value  pk
0     0         Row ID  INTEGER        0       None   0
1     1       Order ID     TEXT        0       None   0
2     2     Order Date     TEXT        0       None   0
3     3      Ship Date     TEXT        0       None   0
4     4      Ship Mode     TEXT        0       None   0
5     5    Customer ID     TEXT        0       None   0
6     6  Customer Name     TEXT        0       None   0
7     7        Segment     TEXT        0       None   0
8     8        Country     TEXT        0       None   0
9     9           City     TEXT        0       None   0
10   10          State     TEXT        0       None   0
11   11    Postal Code  INTEGER        0       None   0
12   12         Region     TEXT        0       None   0
13   13     Product ID     TEXT        0       None   0
14   14       Category     TEXT        0       None   0
15   15   Sub-Category     TEXT        0       None   0
16   16   Product Name     TEXT        0       None   0
17   17          Sales     REAL        0       None   0
18   18       Quantity  INTEGER        0       None   0
19   19       Discount     REAL        0       None   0
20   20         Profit     REAL        0       None   0

Create these 3 tables from it:  
a)customers  
b)orders  
c)products

In [6]:
conn.execute("PRAGMA foreign_keys=ON")

conn.execute("""
             CREATE TABLE customers (
             cust_id TEXT PRIMARY KEY ,
             cust_name TEXT,
             segment TEXT)
            """)

conn.execute("""
            CREATE TABLE orders (
            order_id TEXT PRIMARY KEY , 
            cust_id TEXT,
            order_date TEXT,
            ship_date TEXT,
            ship_mode TEXT, 
            country TEXT,
            city TEXT,
            state TEXT,
            postal_code INTEGER,
            region TEXT,
            FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
            )"""
            )

conn.execute ("""
              CREATE TABLE products (
              prod_id TEXT PRIMARY KEY,
              category TEXT,
              sub_category TEXT,
              prod_name TEXT
              ) """
             )

Insert data into these tables using SELECT DISTINCT.

In [7]:
conn.execute("""
            INSERT INTO customers
            SELECT DISTINCT
            "Customer ID",
            "Customer Name",
            Segment
            FROM superstore_raw""")

In [8]:

conn.execute("""
            INSERT INTO orders
            SELECT DISTINCT
            "Order ID",
            "Customer ID",
            "Order Date",
            "Ship Date",
            "Ship Mode",
            Country,
            City,
            State,
            "Postal Code",
            Region
            FROM superstore_raw""")

In [9]:
conn.execute("""
            INSERT INTO products
            SELECT
            "Product ID",
            MAX(Category),
            MAX("Sub-Category"),
            MAX("Product Name")
            FROM superstore_raw
            GROUP BY "Product ID"
            """)

In [10]:
pd.read_sql_query( " SELECT * FROM customers LIMIT 10",conn)

    cust_id           cust_name      segment
0  CG-12520         Claire Gute     Consumer
1  DV-13045     Darrin Van Huff    Corporate
2  SO-20335      Sean O'Donnell     Consumer
3  BH-11710     Brosina Hoffman     Consumer
4  AA-10480        Andrew Allen     Consumer
5  IM-15070        Irene Maddox     Consumer
6  HP-14815       Harold Pawlan  Home Office
7  PK-19075           Pete Kriz     Consumer
8  AG-10270     Alejandro Grove     Consumer
9  ZD-21925  Zuschuss Donatelli     Consumer

In [11]:
pd.read_sql_query( " SELECT * FROM orders LIMIT 10",conn)

,order_id,cust_id,order_date,ship_date,ship_mode,country,city,state,postal_code,region
0,CA-2016-152156,CG-12520,11/8/2016,11/11/2016,Second Class,United States,Henderson,Kentucky,42420,South
1,CA-2016-138688,DV-13045,6/12/2016,6/16/2016,Second Class,United States,Los Angeles,California,90036,West
2,US-2015-108966,SO-20335,10/11/2015,10/18/2015,Standard Class,United States,Fort Lauderdale,Florida,33311,South
3,CA-2014-115812,BH-11710,6/9/2014,6/14/2014,Standard Class,United States,Los Angeles,California,90032,West
4,CA-2017-114412,AA-10480,4/15/2017,4/20/2017,Standard Class,United States,Concord,North Carolina,28027,South
5,CA-2016-161389,IM-15070,12/5/2016,12/10/2016,Standard Class,United States,Seattle,Washington,98103,West
6,US-2015-118983,HP-14815,11/22/2015,11/26/2015,Standard Class,United States,Fort Worth,Texas,76106,Central
7,CA-2014-105893,PK-19075,11/11/2014,11/18/2014,Standard Class,United States,Madison,Wisconsin,53711,Central
8,CA-2014-167164,AG-10270,5/13/2014,5/15/2014,Second Class,United States,West Jordan,Utah,84084,West
9,CA-2014-143336,ZD-21925,8/27/2014,9/1/2014,Second Class,United States,San Francisco,California,94109,West

In [12]:
pd.read_sql_query( " SELECT * FROM products LIMIT 10",conn)

,prod_id,category,sub_category,prod_name
0,FUR-BO-10000112,Furniture,Bookcases,"Bush Birmingham Collection Bookcase, Dark Cherry"
1,FUR-BO-10000330,Furniture,Bookcases,"Sauder Camden County Barrister Bookcase, Plank..."
2,FUR-BO-10000362,Furniture,Bookcases,Sauder Inglewood Library Bookcases
3,FUR-BO-10000468,Furniture,Bookcases,O'Sullivan 2-Shelf Heavy-Duty Bookcases
4,FUR-BO-10000711,Furniture,Bookcases,"Hon Metal Bookcases, Gray"
5,FUR-BO-10000780,Furniture,Bookcases,O'Sullivan Plantations 2-Door Library in Landv...
6,FUR-BO-10001337,Furniture,Bookcases,O'Sullivan Living Dimensions 2-Shelf Bookcases
7,FUR-BO-10001519,Furniture,Bookcases,O'Sullivan 3-Shelf Heavy-Duty Bookcases
8,FUR-BO-10001567,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Dark Cher..."
9,FUR-BO-10001601,Furniture,Bookcases,"Sauder Mission Library with Doors, Fruitwood F..."

### Step 2: Perform Required Queries

Create new table for order details and insert values in it.

In [13]:
conn.execute("""
             CREATE TABLE order_details(
             order_id TEXT,
             prod_id TEXT,
             sales REAL,
             quantity INTEGER,
             discount REAL,
             profit REAL,
             FOREIGN KEY(order_id) REFERENCES orders(order_id),
             FOREIGN KEY(prod_id) REFERENCES products(prod_id))
             """)

In [14]:
conn.execute("""INSERT INTO order_details
            SELECT
            "Order ID",
            "Product ID",
            Sales,
            Quantity,
            Discount,
            Profit
            FROM superstore_raw;""")

In [15]:
pd.read_sql_query( " SELECT * FROM order_details LIMIT 10",conn)

         order_id          prod_id     sales  quantity  discount    profit
0  CA-2016-152156  FUR-BO-10001798  261.9600         2      0.00   41.9136
1  CA-2016-152156  FUR-CH-10000454  731.9400         3      0.00  219.5820
2  CA-2016-138688  OFF-LA-10000240   14.6200         2      0.00    6.8714
3  US-2015-108966  FUR-TA-10000577  957.5775         5      0.45 -383.0310
4  US-2015-108966  OFF-ST-10000760   22.3680         2      0.20    2.5164
5  CA-2014-115812  FUR-FU-10001487   48.8600         7      0.00   14.1694
6  CA-2014-115812  OFF-AR-10002833    7.2800         4      0.00    1.9656
7  CA-2014-115812  TEC-PH-10002275  907.1520         6      0.20   90.7152
8  CA-2014-115812  OFF-BI-10003910   18.5040         3      0.20    5.7825
9  CA-2014-115812  OFF-AP-10002892  114.9000         5      0.00   34.4700

## 1.Find all orders where sales are greater than the average sales. (Subquery)

In [16]:
pd.read_sql_query( "SELECT AVG(sales) FROM order_details",conn)

   AVG(sales)
0  229.858001

In [17]:

pd.read_sql_query( """SELECT *,
                              (SELECT AVG(sales) FROM order_details) as avg_sales
                      FROM order_details 
                      WHERE sales > (
                                      SELECT AVG(sales) 
                                      FROM order_details
                                    )""",conn)

,order_id,prod_id,sales,quantity,discount,profit,avg_sales
0,CA-2016-152156,FUR-BO-10001798,261.9600,2,0.00,41.9136,229.858001
1,CA-2016-152156,FUR-CH-10000454,731.9400,3,0.00,219.5820,229.858001
2,US-2015-108966,FUR-TA-10000577,957.5775,5,0.45,-383.0310,229.858001
3,CA-2014-115812,TEC-PH-10002275,907.1520,6,0.20,90.7152,229.858001
4,CA-2014-115812,FUR-TA-10001539,1706.1840,9,0.20,85.3092,229.858001
...,...,...,...,...,...,...,...
2355,US-2016-103674,TEC-PH-10004080,271.9600,5,0.20,27.1960,229.858001
2356,US-2016-103674,TEC-PH-10002496,249.5840,2,0.20,31.1980,229.858001
2357,US-2016-103674,OFF-BI-10002026,437.4720,14,0.20,153.1152,229.858001
2358,CA-2017-121258,TEC-PH-10003645,258.5760,2,0.20,19.3932,229.858001
2359,CA-2017-119914,OFF-AP-10002684,243.1600,2,0.00,72.9480,229.858001

The query uses a subquery in the WHERE clause to calculate the average sales and returns all orders whose sales are greater than that average.

## 2.Find the highest sales order for each customer. (Subquery)

In [18]:
pd.read_sql_query("""
                SELECT 
                c.cust_name,     t1.cust_id,        t1.order_id as highest_sales_order ,     t1.order_sales
                FROM
                (
                    SELECT
                    o.cust_id,          o.order_id,         SUM(od.sales) AS order_sales
                    FROM orders o
                    JOIN order_details od
                    ON o.order_id = od.order_id
                    GROUP BY o.cust_id, o.order_id
                )
                t1
                JOIN customers c
                ON c.cust_id = t1.cust_id
                WHERE order_sales =
                (
                    SELECT MAX(t2.order_sales)
                    FROM
                    (
                        SELECT 
                        o.cust_id,       o.order_id,          SUM(od.sales) AS order_sales
                        FROM orders o
                        JOIN order_details od
                        ON o.order_id = od.order_id
                        GROUP BY o.cust_id, o.order_id
                    ) 
                    t2
                    WHERE t2.cust_id = t1.cust_id
                )
                """,conn)

              cust_name   cust_id highest_sales_order  order_sales
0            Alex Avila  AA-10315      CA-2016-103982     4406.072
1          Allen Armold  AA-10375      CA-2016-131065      513.520
2          Andrew Allen  AA-10480      CA-2016-114601     1157.980
3         Anna Andreadi  AA-10645      CA-2015-110863     1971.460
4         Aaron Bergman  AB-10015      CA-2016-140935      563.940
..                  ...       ...                 ...          ...
788        Xylona Preis  XP-21865      CA-2014-167927      708.616
789      Yoseph Carroll  YC-21895      CA-2014-119375     3116.490
790       Yana Sorensen  YS-21880      CA-2017-119809     3859.488
791    Zuschuss Carroll  ZC-21910      CA-2015-115567     1716.160
792  Zuschuss Donatelli  ZD-21925      CA-2016-152471      839.944

[793 rows x 4 columns]

Execution Order:

- FROM : Creates table t1 containing cust_id, order_id and total sales for each order.
- WHERE : For each row of t1, correlated subquery t2 finds the maximum order_sales for that customer using t2.cust_id = t1.cust_id.
- WHERE : Retains only those rows whose order_sales equals the maximum order_sales for that customer.
- SELECT : Displays cust_name, cust_id, highest_sales_order_id and the corresponding order_sales.

## 3.Calculate total sales for each customer. (CTE)

In [19]:
pd.read_sql_query("""
                    WITH cust_sales AS
                    (
                        SELECT 
                        o.cust_id,       SUM(od.sales) AS total_sales
                        FROM orders o
                        JOIN order_details od
                          ON o.order_id = od.order_id
                        GROUP BY o.cust_id
                    )
                    
                    SELECT 
                    c.cust_name,      cs.cust_id,            cs.total_sales
                    FROM cust_sales cs
                    JOIN customers c
                      ON cs.cust_id = c.cust_id
                    """,conn)

              cust_name   cust_id  total_sales
0            Alex Avila  AA-10315     5563.560
1          Allen Armold  AA-10375     1056.390
2          Andrew Allen  AA-10480     1790.512
3         Anna Andreadi  AA-10645     5086.935
4         Aaron Bergman  AB-10015      886.156
..                  ...       ...          ...
788        Xylona Preis  XP-21865     2374.658
789      Yoseph Carroll  YC-21895     5454.350
790       Yana Sorensen  YS-21880     6720.444
791    Zuschuss Carroll  ZC-21910     8025.707
792  Zuschuss Donatelli  ZD-21925     1493.944

[793 rows x 3 columns]


CTE query=>
- FROM : Joins orders and order_details using order_id to associate each sale with a customer.
- GROUP BY : Groups records by cust_id and calculates total_sales for each customer using SUM(sales).
- WITH(CTE) : Creates a temporary result set named cust_sales containing cust_id anad total_sales.

Main query =>
- FROM : Joins the CTE cust_sales with customers using cust_id.
- SELECT : Displays cust_name, cust_id and total_sales.

## 4.Find customers whose total sales are above average. (CTE + Subquery)

In [50]:
pd.read_sql_query("""
                    WITH cust_sales AS
                    (
                        SELECT
                        o.cust_id,           SUM(od.sales) AS total_sales
                        FROM orders o
                        JOIN order_details od
                          ON o.order_id = od.order_id
                        GROUP BY o.cust_id
                    )
                    
                    SELECT
                    c.cust_name,    cs.cust_id,           cs.total_sales
                    FROM cust_sales cs
                    JOIN customers c
                                  ON cs.cust_id = c.cust_id
                    WHERE cs.total_sales >
                                            (
                                                SELECT AVG(total_sales)
                                                FROM cust_sales
                                            )
                    """,conn)

            cust_name   cust_id  total_sales
0          Alex Avila  AA-10315     5563.560
1       Anna Andreadi  AA-10645     5086.935
2     Adam Bellavance  AB-10060     7755.620
3       Adrian Barton  AB-10105    14473.571
4             Amy Cox  AC-10450     5527.846
..                ...       ...          ...
289   Victoria Wilson  VW-21775     6134.038
290     William Brown  WB-21850     6160.102
291    Yoseph Carroll  YC-21895     5454.350
292     Yana Sorensen  YS-21880     6720.444
293  Zuschuss Carroll  ZC-21910     8025.707

[294 rows x 3 columns]

CTE Quer=>
- FROM : Joins orders and order_details using order_id to associate each sale with a customer.
- GROUP BY : Groups records by cust_id and calculates total_sales for each customer using SUM(sales).
- WITH(CTE) :Temporary set containing cust_id and total_sales.

Main Query=>
- FROM : Joins the CTE with customers using cust_id.
- WHERE : Uses a subquery to calculate the aveg total_sales of all customers from CTE and retains only customers whose tot_sales is greater than average.
- SELECT : Displays cust_name, cust_id and total_sales of customers whose total sales are above average.

## 5. Rank all customers based on total sales. (Window Function)

In [49]:
pd.read_sql_query(
                """
                WITH cust_sales AS
                (
                    SELECT
                                o.cust_id,         SUM(od.sales) AS tot_sales
                    FROM orders o
                    JOIN order_details od
                                    ON o.order_id = od.order_id
                    GROUP BY o.cust_id
                )
                
                SELECT
                    c.cust_name,             cs.cust_id,               cs.tot_sales,            
                    RANK() OVER (ORDER BY cs.tot_sales DESC) AS rank
                FROM cust_sales cs
                JOIN customers c  
                                ON cs.cust_id = c.cust_id;
                """,conn)

           cust_name   cust_id  tot_sales  rank
0        Sean Miller  SM-20320  25043.050     1
1       Tamara Chand  TC-20980  19052.218     2
2       Raymond Buch  RB-19360  15117.339     3
3       Tom Ashbrook  TA-21385  14595.620     4
4      Adrian Barton  AB-10105  14473.571     5
..               ...       ...        ...   ...
788       Roy Skaria  RS-19870     22.328   789
789  Mitch Gastineau  MG-18205     16.739   790
790     Carl Jackson  CJ-11875     16.520   791
791     Lela Donovan  LD-16855      5.304   792
792    Thais Sissman  TS-21085      4.833   793

[793 rows x 4 columns]

CTE Query=>
- FROM : Joins orders and order_details using order_id to associate each sale with a customer.
- GROUP BY : Groups records by cust_id and calculates tot_sales for each customer using SUM(sales).
- WITH (CTE) : Creates a temporary set named cust_sales containing cust_id and tot_sales.

Main Query=>
- FROM : Joins the CTE cust_sales with customers using cust_id.
- SELECT : Retrieves cust_name, cust_id and tot_sales.
- WINDOW FUNCTION : Used RANK() to assign ranks to customers based on total sales.

## 6.Assign row numbers to each order within a customer. (Window Function + PARTITION BY)

In [48]:
pd.read_sql_query(
                """
                SELECT
                        o.cust_id,             o.order_id,             o.order_date,
                        ROW_NUMBER() OVER
                        (
                            PARTITION BY o.cust_id
                            ORDER BY o.order_date
                        ) AS row_num
                FROM orders o;
                """,conn)

       cust_id        order_id order_date  row_num
0     AA-10315  CA-2015-121391  10/4/2015        1
1     AA-10315  CA-2016-103982   3/3/2016        2
2     AA-10315  CA-2014-128055  3/31/2014        3
3     AA-10315  CA-2017-147039  6/29/2017        4
4     AA-10315  CA-2014-138100  9/15/2014        5
...        ...             ...        ...      ...
5004  ZD-21925  CA-2016-167682   4/3/2016        1
5005  ZD-21925  US-2016-147991   5/5/2016        2
5006  ZD-21925  CA-2017-141481  6/11/2017        3
5007  ZD-21925  CA-2016-152471   7/8/2016        4
5008  ZD-21925  CA-2014-143336  8/27/2014        5

[5009 rows x 4 columns]

- PARTITION BY o.cust_id creates separate groups for each customer.
- ORDER BY o.order_date arranges the customer's orders by date before assigning numbers.
- ROW_NUMBER() gives a unique sequential number 1, 2, 3... to each order within that customer group.

## 7.Display top 3 customers based on total sales. (Window Function)

In [47]:
pd.read_sql_query(
                """
                WITH cust_sales AS
                (
                    SELECT
                            o.cust_id,         SUM(od.sales) AS tot_sales
                    FROM orders o
                    JOIN order_details od 
                                        ON o.order_id = od.order_id
                    GROUP BY o.cust_id
                )

                SELECT
                    c.cust_name,             cs.cust_id,             cs.tot_sales
                FROM
                (
                    SELECT
                            cust_id,             tot_sales,
                        ROW_NUMBER() OVER (ORDER BY tot_sales DESC) AS rn
                    FROM cust_sales
                ) cs
                JOIN customers c 
                                ON cs.cust_id = c.cust_id
                WHERE cs.rn<=3;
                """,conn)

      cust_name   cust_id  tot_sales
0   Sean Miller  SM-20320  25043.050
1  Tamara Chand  TC-20980  19052.218
2  Raymond Buch  RB-19360  15117.339

- First, total sales are calculated for each customer using SUM(sales).
- ROW_NUMBER() ranks customers from highest to lowest sales.
- WHERE rn<=3 keeps only the top 3 customers with the highest sales.

# Final Combined Query

Write one final query that shows: 

- Customer Name  
- Total Sales  
- Rank  

(Use JOIN + CTE + Window Function together)

In [44]:
pd.read_sql_query(
                """
                WITH cust_sales AS
                (
                    SELECT
                        o.cust_id,         SUM(od.sales) AS tot_sales
                    FROM orders o
                    JOIN order_details od
                                        ON o.order_id = od.order_id
                    GROUP BY o.cust_id
                )

                SELECT
                    c.cust_name,             cs.tot_sales,
                    RANK() OVER (ORDER BY cs.tot_sales DESC) AS rank
                FROM cust_sales cs
                JOIN customers c 
                               ON cs.cust_id = c.cust_id;
                """,conn)

           cust_name  tot_sales  rank
0        Sean Miller  25043.050     1
1       Tamara Chand  19052.218     2
2       Raymond Buch  15117.339     3
3       Tom Ashbrook  14595.620     4
4      Adrian Barton  14473.571     5
..               ...        ...   ...
788       Roy Skaria     22.328   789
789  Mitch Gastineau     16.739   790
790     Carl Jackson     16.520   791
791     Lela Donovan      5.304   792
792    Thais Sissman      4.833   793

[793 rows x 3 columns]

The CTE calculates the total sales for each customer.
JOIN is used to get the customer name from the customers table.
RANK() assigns a rank based on total sales,with the highest sales getting Rank 1.

# Mini Project: Customer Sales Insights

Answer the following using SQL:

## 1. Who are the top 5 customers?

In [42]:
pd.read_sql_query(
                """
                WITH cust_sales AS
                (
                    SELECT
                        o.cust_id,         SUM(od.sales) AS tot_sales
                    FROM orders o
                    JOIN order_details od 
                                        ON o.order_id = od.order_id
                    GROUP BY o.cust_id
                )

                SELECT
                    c.cust_name,             cs.tot_sales
                FROM
                (
                    SELECT
                        cust_id,             tot_sales,
                        ROW_NUMBER() OVER (ORDER BY tot_sales DESC) AS rn
                    FROM cust_sales
                ) cs
                JOIN customers c 
                                ON cs.cust_id = c.cust_id
                WHERE cs.rn <= 5;
                """,conn)

       cust_name  tot_sales
0    Sean Miller  25043.050
1   Tamara Chand  19052.218
2   Raymond Buch  15117.339
3   Tom Ashbrook  14595.620
4  Adrian Barton  14473.571

- First, total sales are calculated for each customer.
- ROW_NUMBER() ranks customers from highest to lowest sales.

## 2.Who are the bottom 5 customers?

In [41]:
pd.read_sql_query(
                """
                WITH cust_sales AS
                (
                    SELECT
                        o.cust_id,         SUM(od.sales) AS tot_sales
                    FROM orders o
                    JOIN order_details od 
                                        ON o.order_id = od.order_id
                    GROUP BY o.cust_id
                )

                SELECT
                    c.cust_name,             cs.tot_sales
                FROM
                (
                    SELECT
                        cust_id,             tot_sales,
                        ROW_NUMBER() OVER (ORDER BY tot_sales ASC) AS rn
                    FROM cust_sales
                ) cs
                JOIN customers c 
                                ON cs.cust_id = c.cust_id
                WHERE cs.rn <= 5;
                """,conn)

         cust_name  tot_sales
0    Thais Sissman      4.833
1     Lela Donovan      5.304
2     Carl Jackson     16.520
3  Mitch Gastineau     16.739
4       Roy Skaria     22.328

- Total sales are calculated for each customer.
- Customers are ranked from low to high sales.

## 3.Which customers made only one order?

In [40]:
pd.read_sql_query(
                """
                SELECT
                    c.cust_name,             o.cust_id ,
                    COUNT(o.order_id) AS tot_orders
                FROM orders o
                JOIN customers c 
                                ON o.cust_id= c.cust_id
                GROUP BY 
                                c.cust_name         , o.cust_id
                HAVING COUNT(o.order_id) =1;
                """,conn)

            cust_name   cust_id  tot_orders
0      Anemone Ratner  AR-10570           1
1   Anthony O'Donnell  AO-10810           1
2        Carl Jackson  CJ-11875           1
3        Jenna Caffey  JC-15385           1
4      Jocasta Rupert  JR-15700           1
5        Lela Donovan  LD-16855           1
6     Mitch Gastineau  MG-18205           1
7   Patricia Hirasaki  PH-18790           1
8     Ricardo Emerson  RE-19405           1
9       Roland Murray  RM-19750           1
10  Susan MacKendrick  SM-20905           1
11      Theresa Coyne  TC-21145           1

- COUNT(order_id) counts how many orders each customer placed.
- GROUP BY creates one row per customer.

# 4.Which customers have above-average sales?

In [39]:
pd.read_sql_query(
                """
                WITH cust_sales AS
                (
                    SELECT
                        o.cust_id,         SUM(od.sales) AS tot_sales
                    FROM orders o
                    JOIN order_details od ON o.order_id = od.order_id
                    GROUP BY o.cust_id
                )

                SELECT
                    c.cust_name,             cs.tot_sales,
                    (SELECT AVG(tot_sales) FROM cust_sales) AS avg_sales
                FROM cust_sales cs
                JOIN customers c ON cs.cust_id = c.cust_id
                WHERE cs.tot_sales >
                (
                    SELECT AVG(tot_sales)
                    FROM cust_sales
                );
                """,conn)

            cust_name  tot_sales  avg_sales
0          Alex Avila   5563.560  2896.8485
1       Anna Andreadi   5086.935  2896.8485
2     Adam Bellavance   7755.620  2896.8485
3       Adrian Barton  14473.571  2896.8485
4             Amy Cox   5527.846  2896.8485
..                ...        ...        ...
289   Victoria Wilson   6134.038  2896.8485
290     William Brown   6160.102  2896.8485
291    Yoseph Carroll   5454.350  2896.8485
292     Yana Sorensen   6720.444  2896.8485
293  Zuschuss Carroll   8025.707  2896.8485

[294 rows x 3 columns]

- cust_sales calculates the total sales for each customer.
- The subquery AVG(tot_sales) finds the avg sales of all customers.

## 5.What is the highest order value per customer?

In [36]:
pd.read_sql_query(
                """
                WITH ord_sales AS
                (
                    SELECT
                        o.cust_id,         o.order_id,
                        SUM(od.sales) AS ord_value
                    FROM orders o
                    JOIN order_details od 
                                         ON o.order_id = od.order_id
                    GROUP BY o.cust_id, o.order_id
                )

                SELECT
                    c.cust_name ,             os.cust_id,
                    MAX(os.ord_value) AS highest_order_value
                FROM ord_sales os
                JOIN customers c 
                                ON os.cust_id= c.cust_id
                GROUP BY 
                            c.cust_name, os.cust_id;
                """,conn)

              cust_name   cust_id  highest_order_value
0         Aaron Bergman  AB-10015              563.940
1         Aaron Hawkins  AH-10030              991.260
2        Aaron Smayling  AS-10045             1476.270
3       Adam Bellavance  AB-10060             4438.686
4             Adam Hart  AH-10075             1169.980
..                  ...       ...                  ...
788        Xylona Preis  XP-21865              708.616
789       Yana Sorensen  YS-21880             3859.488
790      Yoseph Carroll  YC-21895             3116.490
791    Zuschuss Carroll  ZC-21910             1716.160
792  Zuschuss Donatelli  ZD-21925              839.944

[793 rows x 3 columns]

- First, the total value of each order is calculated.
- MAX() finds the highest order value for each customer.